
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 * Jednoduchá aplikace do kavárny, kde si zákazník může vybrat pouze jeden nápoj, ale současně více dortů.
 * Následně program spočítá součet, DPH a vše sečně. Dle typu platby se poté částka zaokrouhlí při volbě platbou hotovostí.
 * Tlačítko vyčistti program vyčistí, tlačítko zavřít program zavře.
 * @author marti
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radEsp = new javax.swing.JRadioButton();
        radCap = new javax.swing.JRadioButton();
        radLat = new javax.swing.JRadioButton();
        radWhi = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        chkCro = new javax.swing.JCheckBox();
        chkMuf = new javax.swing.JCheckBox();
        chkChe = new javax.swing.JCheckBox();
        chkCup = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSou = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDph = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCel = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEnt = new javax.swing.JButton();
        btnVyc = new javax.swing.JButton();
        btnZav = new javax.swing.JButton();
        radHot = new javax.swing.JRadioButton();
        radKar = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kavárna");
        jLabel1.setToolTipText("");

        radEsp.setText("Espresso 39 Kč");
        radEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEspActionPerformed(evt);
            }
        });

        radCap.setText("Cappuccino 49 Kč");
        radCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCapActionPerformed(evt);
            }
        });

        radLat.setText("Caffe Latte 49 Kč");
        radLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLatActionPerformed(evt);
            }
        });

        radWhi.setText("Flat White 49 Kč");
        radWhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radWhiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Káva");

        chkCro.setText("Croissant 35 Kč");
        chkCro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCroActionPerformed(evt);
            }
        });

        chkMuf.setText("Muffin 39 Kč");

        chkChe.setText("Cheesecake 39 Kč");

        chkCup.setText("Cupcake 30 Kč");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Dorty");

        jScrollPane1.setViewportView(txtSou);

        jScrollPane2.setViewportView(txtDph);

        jScrollPane3.setViewportView(txtCel);

        jLabel4.setText("Součet");

        jLabel5.setText("DPH");

        jLabel6.setText("Celkem");

        btnEnt.setText("Enter");
        btnEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntActionPerformed(evt);
            }
        });

        btnVyc.setText("Vyčistit");
        btnVyc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVycActionPerformed(evt);
            }
        });

        btnZav.setText("Zavřít");
        btnZav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZavActionPerformed(evt);
            }
        });

        radHot.setText("Hotově");
        radHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHotActionPerformed(evt);
            }
        });

        radKar.setText("Kartou");
        radKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radKarActionPerformed(evt);
            }
        });

        jLabel7.setText("Způsob platby:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnZav, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(85, 85, 85))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnVyc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radHot)
                                    .addComponent(jLabel7)
                                    .addComponent(radKar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radCap)
                                    .addComponent(radEsp)
                                    .addComponent(radWhi)
                                    .addComponent(radLat))
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCro)
                                    .addComponent(chkMuf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkChe)
                                    .addComponent(chkCup, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radEsp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radCap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radLat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radWhi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVyc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZav)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkCro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkMuf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkChe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCup)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radHot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radKar)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEspActionPerformed
        // výběr tlačínka espresso
        if(radEsp.isSelected()){
            radCap.setSelected(false);
            radLat.setSelected(false);
            radWhi.setSelected(false);
        }
    }//GEN-LAST:event_radEspActionPerformed

    private void radCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCapActionPerformed
        // výběr tlačítka capuccino
        if(radCap.isSelected()){
            radEsp.setSelected(false);
            radLat.setSelected(false);
            radWhi.setSelected(false);
        }
    }//GEN-LAST:event_radCapActionPerformed

    private void radLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLatActionPerformed
        // výběr tlačítka Latté
        if(radLat.isSelected()){
            radCap.setSelected(false);
            radEsp.setSelected(false);
            radWhi.setSelected(false);
        }
    }//GEN-LAST:event_radLatActionPerformed

    private void radWhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radWhiActionPerformed
        // výběr tlačítka Flat White
        if(radWhi.isSelected()){
            radCap.setSelected(false);
            radLat.setSelected(false);
            radEsp.setSelected(false);
        }
    }//GEN-LAST:event_radWhiActionPerformed

    private void chkCroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCroActionPerformed

    //metoda pro tlačítko ENTER
    private void btnEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntActionPerformed
        // založení atributů
        DecimalFormat df = new DecimalFormat("0.00 Kč");
        double celkem = 0;
        double soucet = 0;
        double DPH = 0;
        //neměnná sazba daně
        final double sazbaDane = 0.21;
        
        //ceny nápojů
        final double cenaEspresso = 39;
        final double cenaCappucino = 49;
        final double cenaCaffeLatte = 49;
        final double cenaFlatWhite = 49;
        
        //ceny dortů
        final double cenaCroissant = 35;
        final double cenaMuffin = 39;
        final double cenaCheesecake = 39;
        final double cenaCupcake = 30;
        
        //podmínka na přičítání nápojů
       if(radEsp.isSelected()){
           soucet += cenaEspresso;
       }else if(radCap.isSelected()){
           soucet += cenaCappucino;
       }else if(radLat.isSelected()){
           soucet += cenaCaffeLatte;
       }else if(radWhi.isSelected()){
           soucet += cenaFlatWhite;
       }
       
       //podmínky na přičítání dortů
       if(chkCro.isSelected()){
           soucet += cenaCroissant;
       }
       if(chkMuf.isSelected()){
           soucet += cenaMuffin;
       }
       if(chkChe.isSelected()){
           soucet += cenaCheesecake;
       }
       if(chkCup.isSelected()){
           soucet += cenaCupcake;
       }
       
       //parsování součtu a převod na text
       txtSou.setText(Double.toString(soucet));
       soucet = Double.parseDouble(txtSou.getText());
       
       //výpočet daně
       DPH = soucet * sazbaDane;
       
       //výpočet celkem
       celkem = soucet + DPH;
       
       //převod DPH na text
       txtDph.setText(Double.toString(DPH));
       
       //převod celkem na text
       txtCel.setText(Double.toString(celkem));
       
       //nastavení formátu čísla
       txtSou.setText(df.format(soucet));
       txtDph.setText(df.format(DPH));
       
       //podmínka karta vs hotovost
       if(radHot.isSelected()){
           txtCel.setText(df.format(Math.ceil(celkem)));
       }else {
           txtCel.setText(df.format(celkem));
       }
       
        
    }//GEN-LAST:event_btnEntActionPerformed

    private void btnVycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVycActionPerformed
        // vyčistit program po stisknutí tlačítka vyčistit
        radEsp.setSelected(false);
        radCap.setSelected(false);
        radWhi.setSelected(false);
        radLat.setSelected(false);
        chkCro.setSelected(false);
        chkMuf.setSelected(false);
        chkChe.setSelected(false);
        chkCup.setSelected(false);
        
        txtSou.setText("");
        txtDph.setText("");
        txtCel.setText("");
        
        radHot.setSelected(false);
        radKar.setSelected(false);
    }//GEN-LAST:event_btnVycActionPerformed

    private void btnZavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZavActionPerformed
        // zavření programu
        System.exit(0);
    }//GEN-LAST:event_btnZavActionPerformed

    private void radHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHotActionPerformed
        // výběr tlačítka hotově
        if(radHot.isSelected()){
            radKar.setSelected(false);
        }
    }//GEN-LAST:event_radHotActionPerformed

    private void radKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radKarActionPerformed
        // výběr tlačítka kartou
        if(radKar.isSelected()){
            radHot.setSelected(false);
        }
    }//GEN-LAST:event_radKarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnt;
    private javax.swing.JButton btnVyc;
    private javax.swing.JButton btnZav;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkChe;
    private javax.swing.JCheckBox chkCro;
    private javax.swing.JCheckBox chkCup;
    private javax.swing.JCheckBox chkMuf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radCap;
    private javax.swing.JRadioButton radEsp;
    private javax.swing.JRadioButton radHot;
    private javax.swing.JRadioButton radKar;
    private javax.swing.JRadioButton radLat;
    private javax.swing.JRadioButton radWhi;
    private javax.swing.JTextPane txtCel;
    private javax.swing.JTextPane txtDph;
    private javax.swing.JTextPane txtSou;
    // End of variables declaration//GEN-END:variables
}
